import { Supplier, SupplierType } from './types.ts';

export const VEE_ELEVENLABS_AGENT_ID = 'agent_9701k60px56gezba55q83jamzhbk';

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: 'british-airways',
    name: 'British Airways',
    type: SupplierType.Airline,
    logoUrl: '/images/british-airways-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1570299434827-c30b0a8c64b3?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'The UK\'s flagship carrier, connecting travelers worldwide with premium service and a vast global route network.',
    longDescription: 'British Airways, the United Kingdom\'s flagship airline, is renowned for its extensive global network and commitment to premium service.',
    avatarImageUrl: 'https://picsum.photos/seed/ba_avatar/512/512',
    websiteUrl: 'https://www.britishairways.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Zephyr',
  },
  {
    id: 'el-al-israel-airlines',
    name: 'EL AL Israel Airlines',
    type: SupplierType.Airline,
    logoUrl: '/images/el-al-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=2074&auto=format&fit=crop',
    shortDescription: 'Israel\'s national airline, known for world-class security.',
    longDescription: 'EL AL Israel Airlines is the national carrier of Israel.',
    avatarImageUrl: '/images/el-al-logo.png',
    websiteUrl: 'https://www.elal.com/eng/uk',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Charon',
    elevenLabsAgentId: 'agent_4301kcfn2ygeeh393v1mv46v40s0',
    useElevenLabs: true,
  },
  {
    id: 'virgin-atlantic',
    name: 'Virgin Atlantic',
    type: SupplierType.Airline,
    logoUrl: '/images/virgin-atlantic-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1554992309-5a10f3747416?q=80&w=1974&auto=format&fit=crop',
    shortDescription: 'An iconic British airline.',
    longDescription: 'Virgin Atlantic is known for its stylish approach to long-haul travel.',
    avatarImageUrl: 'https://picsum.photos/seed/virgin_avatar/512/512',
    websiteUrl: 'https://www.virginatlantic.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Puck',
  },
  {
    id: 'emirates',
    name: 'Emirates',
    type: SupplierType.Airline,
    logoUrl: '/images/emirates-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1582794711333-6831d3f63b65?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Dubai\'s award-winning airline.',
    longDescription: 'Emirates is world-renowned for its luxury and innovation.',
    avatarImageUrl: 'https://picsum.photos/seed/emirates_avatar/512/512',
    websiteUrl: 'https://www.emirates.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Kore',
  },
  {
    id: 'qatar-airways',
    name: 'Qatar Airways',
    type: SupplierType.Airline,
    logoUrl: '/images/qatar-airways-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1619462879836-8a71d02a3f89?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'A 5-star airline.',
    longDescription: 'Qatar Airways is a multiple award-winning, 5-star airline.',
    avatarImageUrl: 'https://picsum.photos/seed/qatar_avatar/512/512',
    websiteUrl: 'https://www.qatarairways.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Charon',
  },
  {
    id: 'malaysia-airlines',
    name: 'Malaysia Airlines',
    type: SupplierType.Airline,
    logoUrl: '/images/malaysia-airlines-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1596779350144-124c9c7457d5?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Experience Malaysian Hospitality.',
    longDescription: 'Malaysia Airlines is the national carrier of Malaysia.',
    avatarImageUrl: 'https://picsum.photos/seed/malaysia_avatar/512/512',
    websiteUrl: 'https://www.malaysiaairlines.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Fenrir',
  },
  {
    id: 'ritz-carlton-hotels',
    name: 'Ritz Carlton Hotels',
    type: SupplierType.Hotel,
    logoUrl: '/images/ritz-carlton-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Luxury redefined.',
    longDescription: 'The Ritz-Carlton is a global symbol of luxury.',
    avatarImageUrl: 'https://picsum.photos/seed/ritz_avatar/512/512',
    websiteUrl: 'https://www.ritzcarlton.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Kore',
  },
  {
    id: 'leonardo-hotels',
    name: 'Leonardo Hotels',
    type: SupplierType.Hotel,
    logoUrl: '/images/leonardo-hotels-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=2071&auto=format&fit=crop',
    shortDescription: 'Modern European hotel chain.',
    longDescription: 'Leonardo Hotels is prominent across Europe and the UK.',
    avatarImageUrl: 'https://picsum.photos/seed/leo_avatar/512/512',
    websiteUrl: 'https://www.leonardo-hotels.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Puck',
  },
  {
    id: 'four-seasons',
    name: 'Four Seasons',
    type: SupplierType.Hotel,
    logoUrl: '/images/four-seasons-logo.jpg',
    bannerUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'World-renowned luxury hospitality.',
    longDescription: 'Four Seasons is a global leader in luxury hospitality.',
    avatarImageUrl: 'https://picsum.photos/seed/fourseasons_avatar/512/512',
    websiteUrl: 'https://www.fourseasons.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Zephyr',
  },
  {
    id: 'royal-caribbean',
    name: 'Royal Caribbean',
    type: SupplierType.Cruise,
    logoUrl: '/images/royal-caribbean-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1563404227-993c8cf14227?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Innovative ships, global destinations.',
    longDescription: 'Royal Caribbean is known for driving innovation at sea.',
    avatarImageUrl: 'https://picsum.photos/seed/rc_avatar/512/512',
    websiteUrl: 'https://www.royalcaribbean.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Kore',
  },
  {
    id: 'prima-hotels',
    name: 'Prima Hotels',
    type: SupplierType.Hotel,
    logoUrl: '/images/prima-hotels-logo.jpeg',
    bannerUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Leading Israeli hotel chain.',
    longDescription: 'Prima Hotels is one of Israel\'s premier hotel chains.',
    avatarImageUrl: 'https://picsum.photos/seed/prima_avatar/512/512',
    websiteUrl: 'https://www.prima-hotels-israel.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Puck',
  },
];
