import { Supplier, SupplierType } from './types.ts';

export const VEE_ELEVENLABS_AGENT_ID = 'agent_9701k60px56gezba55q83jamzhbk';

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: 'british-airways',
    name: 'British Airways',
    type: SupplierType.Airline,
    logoUrl: '/images/british-airways-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1570299434827-c30b0a8c64b3?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'The UK's flagship carrier, connecting travelers worldwide with premium service and a vast global route network.',
    longDescription: 'British Airways, the United Kingdom\'s flagship airline, is renowned for its extensive global network and commitment to premium service. From its main hubs at London Heathrow and Gatwick, it serves hundreds of destinations worldwide. Travel agents can access information on its various cabin classes, including the luxurious First, the innovative Club World, World Traveller Plus, and World Traveller, as well as details on earning and redeeming Avios points through the Executive Club.',
    avatarImageUrl: 'https://picsum.photos/seed/ba_avatar/512/512',
    websiteUrl: 'https://www.britishairways.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Zephyr',
  },
  {
    id: 'el-al-israel-airlines',
    name: 'EL AL Israel Airlines',
    type: SupplierType.Airline,
    logoUrl: '/images/el-al-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1543699539-a6022c73c5a7?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Israel\'s national airline, known for world-class security, nonstop routes from London Heathrow and London Luton to Tel Aviv, and tailored service.',
    longDescription: 'EL AL Israel Airlines is the national carrier of Israel, celebrated for its stringent security protocols and direct flights to Tel Aviv from major cities worldwide. It offers a range of services for both business and leisure travelers, including a frequent flyer program, Matmid. Our AI can provide details on flight schedules, baggage policies, and special assistance services.',
    avatarImageUrl: '/images/el-al-logo.png',
    websiteUrl: 'https://www.elal.com/eng/uk',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Charon',
    elevenLabsAgentId: 'agent_4301kcfn2ygeeh393v1mv46v40s0',
    useElevenLabs: true,
  },
  {
    id: 'virgin-atlantic',
    name: 'Virgin Atlantic',
    type: SupplierType.Airline,
    logoUrl: '/images/virgin-atlantic-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1554992309-5a10f3747416?q=80&w=1974&auto=format&fit=crop',
    shortDescription: 'An iconic British airline, offering stylish cabins, friendly service, and long-haul flights with a touch of fun.',
    longDescription: 'Virgin Atlantic, founded by Sir Richard Branson, is known for its stylish and innovative approach to long-haul travel. Operating from London Heathrow and Manchester, the airline flies to key destinations across North America, the Caribbean, Africa, and Asia. It features unique cabin experiences like Upper Class with its iconic bar, Premium, and Economy. Our AI can help with route information, Flying Club loyalty program queries, and commission structures.',
    avatarImageUrl: 'https://picsum.photos/seed/virgin_avatar/512/512',
    websiteUrl: 'https://www.virginatlantic.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Puck',
  },
  {
    id: 'emirates',
    name: 'Emirates',
    type: SupplierType.Airline,
    logoUrl: '/images/emirates-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1582794711333-6831d3f63b65?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Dubai's award-winning airline, famous for luxury onboard experiences, modern fleet, and extensive global connectivity.',
    longDescription: 'Emirates is a world-renowned airline based in Dubai, celebrated for its luxury, innovation, and extensive global network. Flying one of the youngest fleets, including the iconic A380, it offers unparalleled onboard experiences like private suites in First Class and the Onboard Lounge. Its hub in Dubai provides seamless connections to over 150 destinations. Ask our AI about its Skywards loyalty program, chauffeur-drive services, and multi-stopover options.',
    avatarImageUrl: 'https://picsum.photos/seed/emirates_avatar/512/512',
    websiteUrl: 'https://www.emirates.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Kore',
  },
  {
    id: 'qatar-airways',
    name: 'Qatar Airways',
    type: SupplierType.Airline,
    logoUrl: '/images/qatar-airways-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1619462879836-8a71d02a3f89?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'A 5-star airline, offering world-class service, Doha hub connectivity, and premium onboard comfort.',
    longDescription: 'Qatar Airways, the state-owned flag carrier of Qatar, is a multiple award-winning, 5-star airline. From its hub at Hamad International Airport in Doha, it connects to over 160 destinations worldwide. It is acclaimed for its Qsuite in Business Class, offering a highly personalized and private experience. Our AI can provide details on its network, Privilege Club loyalty program, and multi-destination booking policies.',
    avatarImageUrl: 'https://picsum.photos/seed/qatar_avatar/512/512',
    websiteUrl: 'https://www.qatarairways.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Charon',
  },
  {
    id: 'malaysia-airlines',
    name: 'Malaysia Airlines',
    type: SupplierType.Airline,
    logoUrl: '/images/malaysia-airlines-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1596779350144-124c9c7457d5?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Experience Malaysian Hospitality with world-class service to destinations across the globe.',
    longDescription: 'Malaysia Airlines is the national carrier of Malaysia, famed for its signature Malaysian Hospitality. Operating from its main hub in Kuala Lumpur International Airport (KLIA), it is a member of the oneworld alliance, offering seamless connectivity to a vast network of destinations across Asia, Australia, Europe, and the Middle East.',
    avatarImageUrl: 'https://picsum.photos/seed/malaysia_avatar/512/512',
    websiteUrl: 'https://www.malaysiaairlines.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Fenrir',
  },
  {
    id: 'ritz-carlton-hotels',
    name: 'Ritz Carlton Hotels',
    type: SupplierType.Hotel,
    logoUrl: '/images/ritz-carlton-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Luxury redefined, delivering legendary service and unforgettable stays in the world's most iconic destinations.',
    longDescription: 'The Ritz-Carlton is a global symbol of luxury, with an unwavering commitment to service excellence. With a portfolio of iconic hotels and resorts in premier destinations, it offers unforgettable experiences tailored to each guest. As part of Marriott Bonvoy, it allows for extensive loyalty benefits. Our AI rep can assist with property details, room types, and the STARS & Luminous travel advisor programs.',
    avatarImageUrl: 'https://picsum.photos/seed/ritz_avatar/512/512',
    websiteUrl: 'https://www.ritzcarlton.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Kore',
  },
  {
    id: 'leonardo-hotels',
    name: 'Leonardo Hotels',
    type: SupplierType.Hotel,
    logoUrl: '/images/leonardo-hotels-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=2071&auto=format&fit=crop',
    shortDescription: 'Modern European hotel chain, blending comfort and design across city and resort locations.',
    longDescription: 'Leonardo Hotels is a prominent hotel chain with a strong presence across Europe and the UK. Known for its modern design, central locations, and excellent value, it caters to both business and leisure travelers. The brand family includes Leonardo Royal, Leonardo Boutique, and NYX Hotels. Our AI can provide information on property locations, amenities, and group booking policies.',
    avatarImageUrl: 'https://picsum.photos/seed/leo_avatar/512/512',
    websiteUrl: 'https://www.leonardo-hotels.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Puck',
  },
  {
    id: 'four-seasons',
    name: 'Four Seasons',
    type: SupplierType.Hotel,
    logoUrl: '/images/four-seasons-logo.jpg',
    bannerUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'World-renowned luxury hospitality, offering exceptional service and experiences in premier global destinations.',
    longDescription: 'Four Seasons Hotels and Resorts is a global leader in luxury hospitality, operating a portfolio of more than 100 hotels and resorts in major city centers and resort destinations in 47 countries. Known for its highly personalized 24-hour service, elegant accommodations, and focus on guest experience, Four Seasons is a preferred choice for discerning travelers. Our AI can provide details on specific properties, the Four Seasons Preferred Partner program, and exclusive amenities for agents to offer clients.',
    avatarImageUrl: 'https://picsum.photos/seed/fourseasons_avatar/512/512',
    websiteUrl: 'https://www.fourseasons.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Zephyr',
  },
  {
    id: 'royal-caribbean',
    name: 'Royal Caribbean',
    type: SupplierType.Cruise,
    logoUrl: '/images/royal-caribbean-logo.png',
    bannerUrl: 'https://images.unsplash.com/photo-1563404227-993c8cf14227?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Innovative ships, global destinations, and unforgettable adventures for travelers of all ages on the high seas.',
    longDescription: 'Royal Caribbean International is known for driving innovation at sea and has continuously redefined cruise vacationing since its launch in 1969. Each successive class of ships is an architectural marvel and pushes the envelope of what is possible on a cruise ship. The cruise line\'s itineraries call on more than 270 destinations in 60 countries on six continents. Our AI can assist with ship details, itineraries, and booking information through CruisingPower.',
    avatarImageUrl: 'https://picsum.photos/seed/rc_avatar/512/512',
    websiteUrl: 'https://www.royalcaribbean.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Kore',
  },
  {
    id: 'prima-hotels',
    name: 'Prima Hotels',
    type: SupplierType.Hotel,
    logoUrl: '/images/prima-hotels-logo.jpeg',
    bannerUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=2070&auto=format&fit=crop',
    shortDescription: 'Leading Israeli hotel chain offering premium accommodations and exceptional service in prime locations across Israel.',
    longDescription: 'Prima Hotels is one of Israel\'s premier hotel chains, with a distinguished portfolio of properties in Tel Aviv, Jerusalem, Eilat, and other key destinations throughout Israel.',
    avatarImageUrl: 'https://picsum.photos/seed/prima_avatar/512/512',
    websiteUrl: 'https://www.prima-hotels-israel.com',
    knowledgeBaseUrl: '',
    knowledgeBaseText: '',
    geminiVoiceName: 'Puck',
  },
];